// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_netinf
void test_netinf();
RcppExport SEXP NetworkInference_test_netinf() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_netinf();
    return R_NilValue;
END_RCPP
}
// netinf_
List netinf_(IntegerVector node_ids, CharacterVector node_names, List cascade_ids, List cascade_times, int model, double alpha, int n_iter);
RcppExport SEXP NetworkInference_netinf_(SEXP node_idsSEXP, SEXP node_namesSEXP, SEXP cascade_idsSEXP, SEXP cascade_timesSEXP, SEXP modelSEXP, SEXP alphaSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type node_ids(node_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type node_names(node_namesSEXP);
    Rcpp::traits::input_parameter< List >::type cascade_ids(cascade_idsSEXP);
    Rcpp::traits::input_parameter< List >::type cascade_times(cascade_timesSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    __result = Rcpp::wrap(netinf_(node_ids, node_names, cascade_ids, cascade_times, model, alpha, n_iter));
    return __result;
END_RCPP
}
