# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_hashmap_ <- function(n_keys) {
    .Call(`_NetworkInference_test_hashmap_`, n_keys)
}

test_hashmap2_ <- function(n_keys) {
    .Call(`_NetworkInference_test_hashmap2_`, n_keys)
}

count_possible_edges_ <- function(cascade_nodes, cascade_times) {
    .Call(`_NetworkInference_count_possible_edges_`, cascade_nodes, cascade_times)
}

netinf_ <- function(node_ids, cascade_nodes, cascade_times, n_edges, model, lambda) {
    .Call(`_NetworkInference_netinf_`, node_ids, cascade_nodes, cascade_times, n_edges, model, lambda)
}

