# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_possible_edges_ <- function(cascade_nodes, cascade_times) {
    .Call(`_NetworkInference_count_possible_edges_`, cascade_nodes, cascade_times)
}

netinf_ <- function(node_ids, cascade_nodes, cascade_times, n_edges, model, lambda, quiet) {
    .Call(`_NetworkInference_netinf_`, node_ids, cascade_nodes, cascade_times, n_edges, model, lambda, quiet)
}

